# Generated by Django 3.1.6 on 2021-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210210_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.PositiveIntegerField(null=True, verbose_name='рейтинг'),
        ),
    ]
